import type { ToolDefinition } from './tool-detector.js';

export const KALI_TOOLS: ToolDefinition[] = [
  { name: 'Nmap', versionCommand: 'nmap --version', versionRegex: /Nmap version (\S+)/i, binaryNames: ['nmap'] },
  { name: 'SQLMap', versionCommand: 'sqlmap --version', versionRegex: /sqlmap\/(\S+)/i, binaryNames: ['sqlmap'] },
  { name: 'Metasploit', versionCommand: 'msfconsole --version', versionRegex: /Framework Version:\s*(\S+)/i, binaryNames: ['msfconsole', 'msfvenom'] },
  { name: 'Nikto', versionCommand: 'nikto -Version', versionRegex: /nikto version (\S+)/i, binaryNames: ['nikto'] },
  { name: 'Hydra', versionCommand: 'hydra', versionRegex: /Hydra v(\S+)/i, binaryNames: ['hydra'] },
  { name: 'John the Ripper', versionCommand: 'john --version', versionRegex: /(\d+\.\d+\.\d+)/, binaryNames: ['john'] },
  { name: 'Hashcat', versionCommand: 'hashcat --version', versionRegex: /(\S+)/, binaryNames: ['hashcat'] },
  { name: 'WPScan', versionCommand: 'wpscan --version', versionRegex: /WPScan (\S+)/i, binaryNames: ['wpscan'] },
  { name: 'Gobuster', versionCommand: 'gobuster --version', versionRegex: /gobuster(\S+)/i, binaryNames: ['gobuster'] },
  { name: 'Dirb', versionCommand: 'dirb', versionRegex: /Dirb\s+(\S+)/i, binaryNames: ['dirb'] },
  { name: 'WFuzz', versionCommand: 'wfuzz --version', versionRegex: /Wfuzz\s+(\S+)/i, binaryNames: ['wfuzz'] },
  { name: 'WhatWeb', versionCommand: 'whatweb --version', versionRegex: /WhatWeb version (\S+)/i, binaryNames: ['whatweb'] },
  { name: 'Burp Suite', versionCommand: 'burpsuite --version 2>/dev/null || java -jar /usr/share/burpsuite/burpsuite.jar --version 2>/dev/null', versionRegex: /Burp Suite (\S+)/i, binaryNames: ['burpsuite'] },
  { name: 'ZAP', versionCommand: 'zap.sh -version', versionRegex: /(\d+\.\d+\.\d+)/, binaryNames: ['zap.sh'] },
  { name: 'Aircrack-ng', versionCommand: 'aircrack-ng --version', versionRegex: /Aircrack-ng (\S+)/i, binaryNames: ['aircrack-ng'] },
  { name: 'Wireshark', versionCommand: 'wireshark --version', versionRegex: /Wireshark (\S+)/i, binaryNames: ['wireshark'] },
  { name: 'TShark', versionCommand: 'tshark --version', versionRegex: /TShark (\S+)/i, binaryNames: ['tshark'] },
  { name: 'Netcat', versionCommand: 'nc -h 2>&1', versionRegex: /(\S+)/, binaryNames: ['nc', 'netcat'] },
  { name: 'Socat', versionCommand: 'socat -V', versionRegex: /socat version (\S+)/i, binaryNames: ['socat'] },
  { name: 'Enum4Linux', versionCommand: 'enum4linux', versionRegex: /enum4linux v(\S+)/i, binaryNames: ['enum4linux'] },
  { name: 'SmbClient', versionCommand: 'smbclient -V', versionRegex: /Version (\S+)/i, binaryNames: ['smbclient'] },
  { name: 'OpenSSL', versionCommand: 'openssl version', versionRegex: /OpenSSL (\S+)/i, binaryNames: ['openssl'] },
  { name: 'GnuPG', versionCommand: 'gpg --version', versionRegex: /gpg \(GnuPG\) (\S+)/i, binaryNames: ['gpg'] },
  { name: 'Searchsploit', versionCommand: 'searchsploit --version', versionRegex: /Searchsploit (\S+)/i, binaryNames: ['searchsploit'] },
  { name: 'Recon-ng', versionCommand: 'recon-ng --version', versionRegex: /(\S+)/, binaryNames: ['recon-ng'] },
  { name: 'TheHarvester', versionCommand: 'theHarvester --version', versionRegex: /(\S+)/i, binaryNames: ['theHarvester'] },
  { name: 'Dnsrecon', versionCommand: 'dnsrecon --version', versionRegex: /(\S+)/, binaryNames: ['dnsrecon'] },
  { name: 'Masscan', versionCommand: 'masscan --version', versionRegex: /Masscan version (\S+)/i, binaryNames: ['masscan'] },
  { name: 'Unicornscan', versionCommand: 'unicornscan --version', versionRegex: /(\S+)/, binaryNames: ['unicornscan'] },
  { name: 'Responder', versionCommand: 'responder --version', versionRegex: /Responder (\S+)/i, binaryNames: ['responder'] },
  { name: 'Impacket', versionCommand: 'impacket-smbexec --version 2>&1 || impacket-getArch --version 2>&1', versionRegex: /Impacket v(\S+)/i, binaryNames: ['impacket-smbexec', 'impacket-getArch'] },
  { name: 'BloodHound', versionCommand: 'bloodhound --version', versionRegex: /(\S+)/, binaryNames: ['bloodhound'] },
  { name: 'CrackMapExec', versionCommand: 'crackmapexec --version', versionRegex: /CrackMapExec (\S+)/i, binaryNames: ['crackmapexec', 'netexec'] },
  { name: 'Bettercap', versionCommand: 'bettercap --version', versionRegex: /bettercap (\S+)/i, binaryNames: ['bettercap'] },
  { name: 'Airgeddon', versionCommand: 'airgeddon', versionRegex: /Airgeddon version (\S+)/i, binaryNames: ['airgeddon'] },
  { name: 'Kismet', versionCommand: 'kismet --version', versionRegex: /Kismet (\S+)/i, binaryNames: ['kismet'] },
  { name: 'TCPDump', versionCommand: 'tcpdump --version', versionRegex: /tcpdump version (\S+)/i, binaryNames: ['tcpdump'] },
  { name: 'Fail2Ban', versionCommand: 'fail2ban-client --version', versionRegex: /Fail2Ban v(\S+)/i, binaryNames: ['fail2ban-client'] },
  { name: 'ClamAV', versionCommand: 'clamscan --version', versionRegex: /ClamAV (\S+)/i, binaryNames: ['clamscan'] },
  { name: 'Lynis', versionCommand: 'lynis --version', versionRegex: /Lynis version (\S+)/i, binaryNames: ['lynis'] },
  { name: 'Rkhunter', versionCommand: 'rkhunter --version', versionRegex: /Rootkit Hunter (\S+)/i, binaryNames: ['rkhunter'] },
  { name: 'Chkrootkit', versionCommand: 'chkrootkit -V', versionRegex: /chkrootkit version (\S+)/i, binaryNames: ['chkrootkit'] },
  { name: 'Tiger', versionCommand: 'tiger', versionRegex: /Tiger (\S+)/i, binaryNames: ['tiger'] },
  { name: 'OSSEC', versionCommand: 'ossec-control status', versionRegex: /(\S+)/, binaryNames: ['ossec-control'] },
  { name: 'Wazuh', versionCommand: 'wazuh-control status', versionRegex: /(\S+)/, binaryNames: ['wazuh-control'] },
  { name: 'Snort', versionCommand: 'snort --version', versionRegex: /Snort version (\S+)/i, binaryNames: ['snort'] },
  { name: 'Suricata', versionCommand: 'suricata --version', versionRegex: /Suricata version (\S+)/i, binaryNames: ['suricata'] },
  { name: 'Zeek', versionCommand: 'zeek --version', versionRegex: /zeek version (\S+)/i, binaryNames: ['zeek'] },
];
